#!/bin/bash
set -e

IMAGE="ubuntu:14.04"

CMD="apt-get update && apt-get install -y supervisor && apt-get clean"

ID=$(docker run -d $IMAGE /bin/sh -c "$CMD")
docker attach $ID
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null
